services:
  riftarena:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:5001"
      Kestrel__Endpoints__Https__Url: "https://+:5001"
      Kestrel__Endpoints__Https__Certificate__Path: "/app/certificates/localhost.pfx"
      Kestrel__Endpoints__Https__Certificate__Password: ${CERTIFICATE_PASSWORD}
      ConnectionStrings__RiftArena: "Server=db;Database=RiftArena;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
    ports:
      - "5001:5001"
    volumes:
      - ./RiftARENA/certificates:/app/certificates:ro