### REGISTER
POST https://localhost:5001/api/Users/register
Content-Type: application/json

{
    "Nickname": "nickname2",
    "Email": "nickname2@gmail.com",
    "Password": "1234"
}

### 
GET https://localhost:5001/api/Users/

### LOGIN 
POST https://localhost:5001/api/Users/login
Content-Type: application/json

{
    "Nickname": "nickname1",
    "Password": "123"
}

### GET USER BY ID 
GET https://localhost:5001/api/Users/1

### DELETE USER BY ID
DELETE https://localhost:5001/api/Users/2

### UPDATE USER BY ID
PUT https://localhost:5001/api/Users/1

{
    "Email": "nickname1_alterado@gmail.com",
    "Password" : "123"
}