### REGISTER
POST https://localhost:5001/api/Users/register
Content-Type: application/json

{
    "Nickname": "nickname1",
    "Email": "nickname1@gmail.com",
    "Password": "123"
}

### 
GET https://localhost:5001/api/Users/

### LOGIN
POST https://localhost:5001/api/Users/login
Content-Type: application/json

{
    "Nickname": "nickname1",
    "Password": "1234"
}